apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 10
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: bpvcode/rotten-potatoes
          ports:
            - containerPort: 5000 #Same as we are exposing in the Dockerfile
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongo-service #Service name (mongo db service)
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd

---
# APPLICATION SERVICE

apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
  - port: 80 # Default port to web applications
    targetPort: 5000 # Container port
    nodePort: 30000
  type: NodePort
